export enum GitHubLanguage {
  JavaScript = "JavaScript",
  TypeScript = "TypeScript",
  Python = "Python",
  Java = "Java",
  CSharp = "C#",
  CPlusPlus = "C++",
  C = "C",
  Go = "Go",
  Rust = "Rust",
  PHP = "PHP",
  Swift = "Swift",
  Kotlin = "Kotlin",
  Ruby = "Ruby",
  Dart = "Dart",
  Shell = "Shell",
  R = "R",
  HTML = "HTML",
  CSS = "CSS",
  Vue = "Vue",
  SQL = "SQL",
  GraphQL = "GraphQL",
  Terraform = "Terraform",
  Perl = "Perl",
  Scala = "Scala",
  Haskell = "Haskell",
  Lua = "Lua",
  Julia = "Julia",
  ObjectiveC = "Objective-C",
  Elixir = "Elixir",
  Clojure = "Clojure",
  FSharp = "F#",
  Assembly = "Assembly",
  MATLAB = "MATLAB",
  Groovy = "Groovy",
  VBScript = "VBScript",
  Pascal = "Pascal",
  Fortran = "Fortran",
  COBOL = "COBOL",
  Ada = "Ada",
  Lisp = "Lisp",
  Prolog = "Prolog",
}

export enum GitHubTopic {
  WebDevelopment = "web-development",
  MachineLearning = "machine-learning",
  ArtificialIntelligence = "artificial-intelligence",
  DataScience = "data-science",
  DeepLearning = "deep-learning",
  CyberSecurity = "cybersecurity",
  GameDevelopment = "game-development",
  MobileDevelopment = "mobile-development",
  DevOps = "devops",
  CloudComputing = "cloud-computing",
  Blockchain = "blockchain",
  OpenSource = "open-source",
  Algorithms = "algorithms",
  CompetitiveProgramming = "competitive-programming",
  Automation = "automation",
  IoT = "iot",
  EmbeddedSystems = "embedded-systems",
  Robotics = "robotics",
  API = "api",
  Microservices = "microservices",
  Backend = "backend",
  Frontend = "frontend",
  FullStack = "fullstack",
  UIUX = "ui-ux",
  BigData = "big-data",
  QuantumComputing = "quantum-computing",
  NLP = "nlp",
  ComputerVision = "computer-vision",
  EthicalHacking = "ethical-hacking",
  Docker = "docker",
  Kubernetes = "kubernetes",
  Serverless = "serverless",
  SaaS = "saas",
  Fintech = "fintech",
  HealthTech = "healthtech",
  EdTech = "edtech",
  Gaming = "gaming",
  Cryptography = "cryptography",
  Linux = "linux",
  RaspberryPi = "raspberry-pi",
  Arduino = "arduino",
  AI = "ai",
  React = "react",
  Vue = "vue",
  Angular = "angular",
  NodeJS = "nodejs",
  SpringBoot = "spring-boot",
  Django = "django",
  Flask = "flask",
  TensorFlow = "tensorflow",
  PyTorch = "pytorch",
}

export enum GitHubStars {
  LessThan50 = "stars:<50",
  Between50And100 = "stars:50..100",
  Between100And500 = "stars:100..500",
  Between500And1000 = "stars:500..1000",
  Between1000And5000 = "stars:1000..5000",
  Between5000And10000 = "stars:5000..10000",
  MoreThan10000 = "stars:>10000",
}

export enum GitHubSort {
  Stars = "stars",
  Forks = "forks",
  Updated = "updated",
  BestMatch = "",
}

export enum GitHubOrder {
  Ascending = "asc",
  Descending = "desc",
}
